---
kind: GCPBackendPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: ${backend_policy_name}
  namespace: ${namespace_name}
  labels:
    owner: xds-k8s-interop-test
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${service_name}
  default:
    % if draining_timeout_sec:
    connectionDraining:
      drainingTimeoutSec: ${draining_timeout_sec}
    % endif
...
