---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment_name}
  namespace: ${namespace_name}
  labels:
    app: ${app_label}
    deployment_id: ${deployment_id}
    owner: xds-k8s-interop-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_label}
      deployment_id: ${deployment_id}
  template:
    metadata:
      labels:
        app: ${app_label}
        deployment_id: ${deployment_id}
        owner: xds-k8s-interop-test
    spec:
      % if service_account_name:
      serviceAccountName: ${service_account_name}
      % endif
      containers:
        - name: ${deployment_name}
          image: ${image_name}
          imagePullPolicy: Always
          startupProbe:
            tcpSocket:
              port: ${stats_port}
            periodSeconds: 3
            ## Extend the number of probes well beyond the duration of the test
            ## driver waiting for the container to start.
            failureThreshold: 1000
          args:
            - "--server=${server_target}"
            - "--stats_port=${stats_port}"
            - "--qps=${qps}"
            - "--rpc=${rpc}"
            - "--metadata=${metadata}"
            % if secure_mode:
            - "--secure_mode=${secure_mode}"
            % endif
            % if request_payload_size > 0:
            - "--request_payload_size=${request_payload_size}"
            % endif
            % if response_payload_size > 0:
            - "--response_payload_size=${response_payload_size}"
            % endif
            - "--print_response=${print_response}"
            % if enable_csm_observability:
            - "--enable_csm_observability=true"
            % endif
          ports:
            - containerPort: ${stats_port}
          env:
            - name: GRPC_XDS_BOOTSTRAP
              value: "/tmp/grpc-xds/td-grpc-bootstrap.json"
            - name: GRPC_EXPERIMENTAL_XDS_AUTHORITY_REWRITE
              value: "true"
            - name: GRPC_EXPERIMENTAL_XDS_SYSTEM_ROOT_CERTS
              value: "true"
            - name: GRPC_EXPERIMENTAL_XDS_GCP_AUTHENTICATION_FILTER
              value: "true"
            - name: GRPC_XDS_EXPERIMENTAL_ENABLE_RING_HASH
              value: "true"
            - name: GRPC_XDS_EXPERIMENTAL_ENABLE_RETRY
              value: "true"
            - name: GRPC_EXPERIMENTAL_ENABLE_OUTLIER_DETECTION
              value: "true"
            - name: GRPC_EXPERIMENTAL_XDS_CUSTOM_LB_CONFIG
              value: "true"
            - name: GRPC_EXPERIMENTAL_XDS_ENABLE_OVERRIDE_HOST
              value: "true"
            % if enable_dualstack:
            - name: GRPC_EXPERIMENTAL_ENABLE_NEW_PICK_FIRST
              value: "true"
            - name: GRPC_EXPERIMENTAL_XDS_DUALSTACK_ENDPOINTS
              value: "true"
            % endif
            % if csm_workload_name:
            - name: CSM_WORKLOAD_NAME
              value: ${csm_workload_name}
            % endif
            % if csm_canonical_service_name:
            - name: CSM_CANONICAL_SERVICE_NAME
              value: ${csm_canonical_service_name}
            % endif
            % if enable_csm_observability:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME)
            % endif
          volumeMounts:
            - mountPath: /tmp/grpc-xds/
              name: grpc-td-conf
              readOnly: true
          resources:
            limits:
              cpu: 800m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      initContainers:
        - name: grpc-td-init
          image: ${td_bootstrap_image}
          imagePullPolicy: Always
          args:
            - "--output=/tmp/bootstrap/td-grpc-bootstrap.json"
            - "--vpc-network-name=${network}"
            % if xds_server_uri:
            - "--xds-server-uri=${xds_server_uri}"
            % endif
            % if config_mesh:
            - "--config-mesh-experimental=${config_mesh}"
            % endif
            % if generate_mesh_id:
            - "--generate-mesh-id-experimental"
            % endif
            % if is_trusted_xds_server_experimental:
            - "--is-trusted-xds-server-experimental"
            % endif
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/bootstrap/
              name: grpc-td-conf
      volumes:
        - name: grpc-td-conf
          emptyDir:
            medium: Memory
...
